---
title: "Thingamajig"
author: "BT_Raptor"
date: "21/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(data.table)
require(stats)
all_data=fread("C:/Users/ricke/Desktop/Raptor's Data Science/opp.csv")
```

Data Acquisition
```{r}
options(scipen=999)
all_data=na.omit(all_data)
head(all_data)
```

Creating a new dataframe, where we do the column tweaking
```{r}
all_data[,`:=`(hdlngth_2=hdlngth**2,skullw_2=skullw**2,totlngth_2=totlngth**2,
               taill_2=taill**2,footlgth_2=footlgth**2,earconch_2=earconch**2,eye_2=eye**2,
               chest_2=chest**2,belly_2=belly**2)]
all_data[,sex_m:=0]
all_data[sex=='m',sex_m:=1]

all_data[,Pop_Vic:=0]
all_data[Pop=='Vic',Pop_Vic:=1]

all_data[,site_1:=0]
all_data[site==1,site_1:=1]

all_data[,site_2:=0]
all_data[site==2,site_2:=1]

all_data[,site_3:=0]
all_data[site==3,site_3:=1]

all_data[,site_4:=0]
all_data[site==4,site_4:=1]

all_data[,site_5:=0]
all_data[site==5,site_5:=1]

all_data[,site_6:=0]
all_data[site==6,site_6:=1]

all_data[,site_7:=0]
all_data[site==7,site_7:=1]

all_data=all_data[,`:=`(case=NULL,site=NULL,Pop=NULL,sex=NULL)]
head(all_data)
```

Perform Forward Selection and Examine Results
```{r}
model_intercept=lm(age~1,data=all_data)
model_all=lm(age~.,data=all_data)
forward= step(model_all, direction='both', scope=formula(model_all), trace=0)
```


Examine the Coefficients
```{r}
forward$coefficients
```

Examine the Preds
```{r}
preds=predict(forward,all_data)
all_data$preds=round(preds)
all_data=all_data[,c('age','preds')]
head(all_data)
```